name: Build SoulDown for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build the macOS binary
        run: |
          pyinstaller --onefile --windowed souldown.py

      - name: List files in dist folder
        run: ls -la ./dist

      - name: Upload macOS binary
        uses: actions/upload-artifact@v3
        with:
          name: SoulDown-macOS
          path: ./dist/souldown  # Ruta ajustada para reflejar el nombre real del binario
